name = "baldmc-server"
mc_version = "1.18.2"

plugins = [
	{ type = "url", url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot", filename = "floodgate.jar" },
	{ type = "url", url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.0.3/ViaVersion-5.0.3.jar" },
	{ type = "url", url = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.16/BlueMap-3.16-spigot.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/GrimAnticheat/GrimAnticheat/versions/2.3.66/PAPER/grimac-2.3.66.jar" },
	{ type = "url", url = "https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/15.0.2/SkinsRestorer.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.3.146/PAPER/Chunky-1.3.146.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/WasabiThumbs/XClaim/versions/1.14.0/PAPER/xclaim-1.14.0.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/kennytv/Maintenance/versions/4.2.1/PAPER/Maintenance-4.2.1.jar" },
	{ type = "url", url = "https://s3.mcjars.app/spigot/1.18.2/3498/server.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/Black1_TV/Passky/versions/2.4.0/PAPER/Passky-2.4.0.jar" },
	{ type = "url", url = "https://github.com/At87668/MinerTrack/releases/download/1.5.2-beta/MinerTrack-1.5.2-beta.jar" },
	{ type = "url", url = "https://hangarcdn.papermc.io/plugins/Black1_TV/AdminGUI/versions/1.7.0/PAPER/AdminGUI-1.7.0.jar" },
]

[jar]
type = "paper"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[options]
success_line = ""
stop_command = ""
